### ISSUE TITLE
Finding the automic.dll file

### ISSUE THREAD

**Issue by brendanSapience** [JoelWiesmann/WorkflowCommander#1]
Joel,

i couldnt find the automic.dll in the UI  Client, but did find it in the "Application Interface" which contains all the API stuff. that's the one that is supposed to be used, correct?

**Comment by JoelWiesmann** [comment]
Hi Brendan

Yes, that's the correct one. I will make the installation instruction more detailed to reduce potential confusion on this.

Regards
Joel
