### ISSUE TITLE
Powershell Version Required

### ISSUE THREAD

**Issue by brendanSapience** [JoelWiesmann/WorkflowCommander#2]
Hi Joel,

I had a problem with powershell v3, and had to install v4 to solve the problem (see screenshot below).

is Powershell 4 the minimum version of powershell supported?

![capture_powershell3](https://cloud.githubusercontent.com/assets/9252657/21990798/21749b54-dbde-11e6-909c-858985355e95.JPG)

**Comment by brendanSapience** [comment]
correction, the minimum version is v5. See #3 !

**Comment by JoelWiesmann** [comment]
Fixed in development branch e34b2fe46ff0a5f1797e2a810fa294845ab8b671
